proyecto_libreria/libros_app/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name="inicio"),
    path('libro/libros/', LibrosList.as_view(), name="libros"),
    path('libro/libro_agregar/', LibroCreate.as_view(), name="libro_agregar"),
    path('libro/libro_confirm_delete/<int:pk>/',
         LibroDelete.as_view(), name="libro_eliminar"),
    path('libro/libro_actualizar/<int:pk>/',
         LibroUpdate.as_view(), name="libro_actualizar"),
    path('libro/libro_detail/<int:pk>/',
         LibroDetailView.as_view(), name="libro_ver_detalles"),
    path('libro/libros_filtrar', LibroViewFilter.as_view(), name="libros_filtrar"),

    path('autor/autores/', AutoresList.as_view(), name="autores"),
    path('autor/autor_agregar/',  AutorCreate.as_view(), name="autor_agregar"),
    path('autor/autor_confirm_delete/<int:pk>/',
         AutorDelete.as_view(), name="autor_eliminar"),
    path('autor/autor_actualizar/<int:pk>/',
         AutorUpdate.as_view(), name="autor_actualizar"),
    path('autor/autor_detail/<int:pk>/',
         AutorDetailView.as_view(), name="autor_ver_detalles"),
    path('autor/autores_filtrar',
         AutoresViewFilter.as_view(), name="autores_filtrar"),

    path('editorial/editoriales/', EditorialesList.as_view(), name="editoriales"),
    path('editorial/editorial_agregar/',
         EditorialCreate.as_view(), name="editorial_agregar"),
    path('editorial/editorial_confirm_delete/<int:pk>/',
         EditorialDelete.as_view(), name="editorial_eliminar"),
    path('editorial/editorial_actualizar/<int:pk>/',
         EditorialUpdate.as_view(), name="editorial_actualizar"),
    path('editorial/editorial_detail/<int:pk>/',
         EditorialDetailView.as_view(), name="editorial_ver_detalles"),
    path('editorial/editoriales_filtrar',
         EditorialViewFilter.as_view(), name="editoriales_filtrar"),

    path('genero/generos/', GenerosList.as_view(), name="generos"),
    path('genero/genero_agregar/',   GeneroCreate.as_view(), name="genero_agregar"),
    path('genero/genero_confirm_delete/<int:pk>/',
         GeneroDelete.as_view(), name="genero_eliminar"),
    path('genero/genero_actualizar/<int:pk>/',
         GeneroUpdate.as_view(), name="genero_actualizar"),
    path('genero/genero_detail/<int:pk>/',
         GeneroDetailView.as_view(), name="genero_ver_detalles"),
    path('genero/generos_filtrar',
         GenerosViewFilter.as_view(), name="generos_filtrar"),


    path('acerca_de_mi', AcercaDeMi.as_view(), name="acerca_de_mi"),

]

proyecto_libreria/proyecto_libreria/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto_libreria import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('libros_app.urls', 'libros_app'), namespace='libros_app')),
    path('', include(('usuarios_app.urls', 'usuarios_app'), namespace='usuarios_app')),
    ]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

proyecto_libreria/usuarios_app/urls.py
from django.urls import path, include

from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('usuario_update_form/<int:pk>/',
         UsuarioUpdate.as_view(), name="actualizar_usuario"),
    path('user_update_form/<int:pk>/', UserUpdate.as_view(),
         name="actualizar_datos_usuario"),

    path('login/',  MyLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="usuarios_app:login"), name="logout"),
    path('signUp/',  SignUp.as_view(), name="signUp"),

]

proyecto_libreria/libros_app/models.py
from django.db import models
from django.contrib import admin
from django.utils.html import format_html
from django.utils import timezone

# Create your models here.

# Editorial del libro.


class Editorial(models.Model):
    nombre = models.CharField(verbose_name="Editorial", max_length=50)
    foto = models.ImageField(upload_to="editoriales",
                             null=True, blank=True, verbose_name="Editorial")
    ano = models.SmallIntegerField(
        verbose_name="Año de fundacion", blank=True, default=0)
    historia = models.TextField(verbose_name="Historia")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Editorial"
        verbose_name_plural = "Editoriales"

    def __str__(self):
        return self.nombre

    @admin.display(ordering="Historia")
    def Historia(self):
        return format_html(self.historia[:150]+"...")

# Autor del libro.


class Autor(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=50)
    Apellido = models.CharField(verbose_name="Apellido", max_length=50)
    foto = models.ImageField(
        upload_to="autores", null=True, blank=True, verbose_name="Autor")
    fecha_nacimiento = models.DateField(default=timezone.now)
    biografia = models.TextField(verbose_name="Biografía")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

    def __str__(self):
        return self.nombre + " " + self.Apellido

    @admin.display(ordering="biografia")
    def sinopsis(self):
        return format_html(self.description[:150]+"...")

# Género de los libros.


class Genero(models.Model):
    nombre = models.CharField(verbose_name="Género", max_length=50)
    historia = models.TextField(verbose_name="Historia", default="")
    foto = models.ImageField(
        upload_to="generos", null=True, blank=True, verbose_name="Género")

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Género"
        verbose_name_plural = "Géneros"

    def __str__(self):
        return self.nombre

# Libro.


class Libro(models.Model):
    nombre = models.CharField(verbose_name="Libro", max_length=100)
    autor = models.ManyToManyField(Autor, verbose_name="Autores")
    sinopsis = models.TextField(verbose_name="sinopsis", blank=True)

    RATING = [
        (1, "Malo"),
        (2, "Mediocre"),
        (3, "Bueno"),
        (4, "Muy Bueno"),
        (5, "Excelente"),
    ]

    rating = models.PositiveSmallIntegerField(choices=RATING)
    generos = models.ManyToManyField(Genero, verbose_name="Géneros")
    editorial = models.ForeignKey(
        Editorial, verbose_name="Editorial", on_delete=models.CASCADE)
    portada = models.ImageField(
        upload_to="libros", null=True, blank=True, verbose_name="Portada")
    ano_publicacion = models.SmallIntegerField(
        verbose_name="Año de publicacion", blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Libro"
        verbose_name_plural = "Libros"

    def __str__(self):
        return self.nombre

    @admin.display(ordering="rating")
    def estrellas(self):
        stars = "*" * self.rating
        return format_html(f"<span style='color:green;'>{stars}</span>")

    @admin.display(ordering="sinopsis")
    def descripcion(self):
        return format_html(self.description[:150]+"...")

    def get_generos(self):
        return ",".join([str(p) for p in self.generos.all()])

    def get_autores(self):
        return ",".join([str(p) for p in self.autor.all()])

proyecto_libreria/libros_app/forms.py
from django import forms
from .models import Editorial, Autor, Genero, Libro


class LibroForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LibroForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Libro

        fields = ['nombre', 'autor', 'sinopsis', 'rating',
                  'generos', 'editorial', 'portada', 'ano_publicacion']
        RATING = [
            (1, "Mala"),
            (2, "Mediocre"),
            (3, "Buena"),
            (4, "Muy Buena"),
            (5, "Excelente")
        ]
        widgets = {
            'Nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Libro'}),
            'Autores': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Géneros'}),
            'sinopsis': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Libro'}),
            'rating': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Rating'}),
            'generos': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Géneros'}),
            'editorial': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Editorial'}),
            'ano_publicacion': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Año de publicacion'}),
        }

        labels = {
            'name': "",
            'description': ""
        }


class AutorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AutorForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Autor

        fields = ['nombre', 'Apellido', 'foto',
                  'fecha_nacimiento', 'biografia']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'Apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'fecha_nacimiento': forms.DateInput(format='%d/%m/%Y'),
            'biografia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Biografía'}),

        }

        labels = {
            'name': "",
            'description': ""
        }


class EditorialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditorialForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Editorial

        fields = ['nombre', 'ano', 'historia', 'foto']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'ano': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Año de fundación'}),
            'historia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Historia'}),
        }

        labels = {
            'name': "",
            'description': ""
        }


class GeneroForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GeneroForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Genero

        fields = ['nombre', 'historia', 'foto']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'historia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Historia'}),
        }

        labels = {
            'name': "",
            'description': ""
        }

proyecto_libreria/libros_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages


import django_filters

# Create your views here.

# Importaciones de Modelos

from .models import Editorial, Autor, Genero, Libro


from .forms import LibroForm, AutorForm, EditorialForm, GeneroForm

from .filters import LibroFilter, AutorFilter, EditorialFilter, GeneroFilter


# Importaciones de CBV

from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import DetailView


from django_filters.views import FilterView


# CLASS BASED VIEWS

class HomeView(TemplateView):
    template_name = "libros_app/inicio.html"


class LibrosList(ListView):
    model = Libro
    template_name = "libros_app/libro/libro_list.html"


class LibroDetailView(DetailView):
    model = Libro
    template_name = "libros_app/libro/libro_detail.html"


class LibroCreate(CreateView):
    model = Libro
    form_class = LibroForm
    success_url = reverse_lazy('libros_app:libros')
    template_name = "libros_app/libro/libro_form.html"


class LibroDelete(DeleteView):
    model = Libro
    success_url = reverse_lazy('libros_app:libros')
    template_name = "libros_app/libro/libro_confirm_delete.html"


class LibroUpdate(UpdateView):
    model = Libro
    form_class = LibroForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/libro/libro_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:libro_actualizar', args=[self.object.id])+"?ok"


class LibroViewFilter(FilterView):
    model = Libro
    template_name = 'libros_app/libro/libros_filtrar.html'
    paginate_by = 10
    filterset_class = LibroFilter


class AutoresList(ListView):
    model = Autor
    template_name = "libros_app/autor/autor_list.html"


class AutorDetailView(DetailView):
    model = Autor
    template_name = "libros_app/autor/autor_detail.html"


class AutorCreate(CreateView):
    model = Autor
    form_class = AutorForm
    success_url = reverse_lazy('libros_app:autores')
    template_name = "libros_app/autor/autor_form.html"


class AutorDelete(DeleteView):
    model = Autor
    success_url = reverse_lazy('libros_app:autores')
    template_name = "libros_app/autor/autor_confirm_delete.html"


class AutorUpdate(UpdateView):
    model = Autor
    form_class = AutorForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/autor/autor_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:autor_actualizar', args=[self.object.id])+"?ok"


class AutoresViewFilter(FilterView):
    model = Autor
    template_name = 'libros_app/autor/autores_filtrar.html'
    paginate_by = 10
    filterset_class = AutorFilter


class EditorialesList(ListView):
    model = Editorial
    template_name = "libros_app/editorial/editorial_list.html"


class EditorialDetailView(DetailView):
    model = Editorial
    template_name = "libros_app/editorial/editorial_detail.html"


class EditorialCreate(CreateView):
    model = Editorial
    form_class = EditorialForm
    success_url = reverse_lazy('libros_app:editoriales')
    template_name = "libros_app/editorial/editorial_form.html"


class EditorialDelete(DeleteView):
    model = Editorial
    success_url = reverse_lazy('libros_app:editoriales')
    template_name = "libros_app/editorial/editorial_confirm_delete.html"


class EditorialUpdate(UpdateView):
    model = Editorial
    form_class = EditorialForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/editorial/editorial_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:editorial_actualizar', args=[self.object.id])+"?ok"


class EditorialViewFilter(FilterView):
    model = Editorial
    template_name = 'libros_app/editorial/editoriales_filtrar.html'
    paginate_by = 10
    filterset_class = EditorialFilter


class GenerosList(ListView):
    model = Genero
    template_name = "libros_app/genero/genero_list.html"


class GeneroDetailView(DetailView):
    model = Genero
    template_name = "libros_app/genero/genero_detail.html"


class GeneroCreate(CreateView):
    model = Genero
    form_class = GeneroForm
    success_url = reverse_lazy('libros_app:generos')
    template_name = "libros_app/genero/genero_form.html"


class GeneroDelete(DeleteView):
    model = Genero
    success_url = reverse_lazy('libros_app:generos')
    template_name = "libros_app/genero/genero_confirm_delete.html"


class GeneroUpdate(UpdateView):
    model = Genero
    form_class = GeneroForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/genero/genero_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:genero_actualizar', args=[self.object.id])+"?ok"


class GenerosViewFilter(FilterView):
    model = Genero
    template_name = 'libros_app/genero/generos_filtrar.html'
    paginate_by = 10
    filterset_class = GeneroFilter


class AcercaDeMi(TemplateView):
    template_name = "libros_app/acerca_de_mi.html"

proyecto_libreria/libros_app/templates/libros_app/acerca_de_mi.html
{% extends 'libros_app/base.html' %}

{% load static %}

{% block title %}
  Inicio
{% endblock %}

<!-- Acerca de mi -->

{% block content %}
  <div class="container-xxl py-3">
    <div class="d-flex justify-content-center">
      <div class="row align-items-center">
        <div class="col">
          <h1 class="display-5 animated fadeIn mb-4">Sobre mi</h1>
          <h5>Estudiante <span class="text-primary">de ingeniería en informática.</span></h5>
          <p>Mi nombre es Sol, tengo 20 años y soy estudiante de ingeniería en informática, estoy interesada en el desarrollo web, principalmente en el back end.</p>
          <p>
            Me capacité con un curso obteniendo conocimientos de <span>DJANGO</span>, framework de python, CSS, HTML y JavaScript.
          </p>
          <p>Me encantaría tener mis primeras experiencias laborales pronto, y seguir aprendiendo sobre los temas mencionados anteriormente.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

proyecto_libreria/libros_app/templates/libros_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8" />

    <title>
      {% block title %}
        BookParadise
      {% endblock %}
    </title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="{% static 'libros_app/lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'libros_app/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'libros_app/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'libros_app/css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container-xxl bg-white p-0">
      <!-- Navbar Start -->
      <div class="container-fluid nav-bar bg-transparent">
        <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">
          <a href="{% url 'libros_app:inicio' %}" class="navbar-brand d-flex align-items-center text-center">
            <div class="p-2 me-0">
              <img class="img-fluid" src="{% static 'libros_app/images/icon.png' %}" alt="Icon" style="width: 50px; height: 50px;" />
            </div>
            <h1 class="m-0 text-primary">BookParadise</h1>
          </a>
          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto">
              <a class="nav-item nav-link" href="{% url 'libros_app:inicio' %}">Inicio</a>
              <a class="nav-item nav-link" href="{% url 'libros_app:libros' %}">Libros</a>
              <a class="nav-item nav-link" href="{% url 'libros_app:autores' %}">Autores</a>
              <a class="nav-item nav-link" href="{% url 'libros_app:editoriales' %}">Editoriales</a>
              <a class="nav-item nav-link" href="{% url 'libros_app:generos' %}">Géneros</a>
              <a class="nav-item nav-link" href="{% url 'libros_app:acerca_de_mi' %}">Acerca de mí</a>

              {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'usuarios_app:actualizar_usuario' user.id %}"><img src="{% static 'libros_app/images/camera.jpeg' %}" alt="actualizar_foto_usuarios" style="width:30px;height:30px; " /></a>

                <a class="nav-item nav-link" href="{% url 'usuarios_app:actualizar_datos_usuario' user.id %}"><img src="{% static 'libros_app/images/settings.png' %}" alt="actualizar_datos_usuario" style="width:30px;height:30px; " /></a>
              {% endif %}

              <div class="user_option">
                {% if request.user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'usuarios_app:logout' %}">
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <span>Logout</span>
                  </a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'usuarios_app:login' %}">
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <span>Login</span>
                  </a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </div>
      <!-- Navbar End -->

      <!-- Submenu de cada modelo -->

      {% block subMenu %}

      {% endblock %}

      <!-- Contenido de cada modelo -->

      {% block content %}

      {% endblock %}

      <!-- Footer Start -->
      <div class="container-fluid bg-dark text-white-50 footer mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container">
          <div class="copyright">
            <div class="row">
              <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                &copy; <a class="border-bottom" href="#">BookParadise</a>, All Right Reserved.
                <!-- /*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/ -->
                Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Footer End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'libros_app/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'libros_app/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'libros_app/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'libros_app/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'libros_app/js/main.js' %}"></script>
  </body>
</html>

proyecto_libreria/libros_app/templates/libros_app/inicio.html
{% extends 'libros_app/base.html' %}

{% load static %}

{% block title %}
  Inicio
{% endblock %}

{% block content %}
  <div class="container-fluid header bg-white p-0">
    <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
      <div class="col-md-6 p-5 mt-lg-5">
        <h1 class="display-5 animated fadeIn mb-4">Encuentre <span class="text-primary">un libro ideal</span> para usted.</h1>
        <p class="animated fadeIn mb-4 pb-2">BookParadise es una página donde usted podrá encontrar información sobre libros, sus autores, editoriales y géneros.</p>
        <a href="{% url 'libros_app:libros' %}" class="btn btn-primary py-3 px-5 me-3 animated fadeIn">Empiece su búsqueda.</a>
      </div>
      <div class="col-md-6 animated fadeIn">
        <div class="owl-carousel header-carousel">
          <div class="owl-carousel-item">
            <img class="img-fluid" src="{% static 'libros_app/images/slider-img-1.jpg' %}" alt="" />
          </div>
          <div class="owl-carousel-item">
            <img class="img-fluid" src="{% static 'libros_app/images/slider-img-2.jpg' %}" alt="" />
          </div>
          <div class="owl-carousel-item">
            <img class="img-fluid" src="{% static 'libros_app/images/slider-img-3.jpg' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}