proyecto_libreria/libros_app/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name="inicio"),
    path('libro/libros/', LibrosList.as_view(), name="libros"),
    path('libro/libro_agregar/', LibroCreate.as_view(), name="libro_agregar"),
    path('libro/libro_confirm_delete/<int:pk>/',
         LibroDelete.as_view(), name="libro_eliminar"),
    path('libro/libro_actualizar/<int:pk>/',
         LibroUpdate.as_view(), name="libro_actualizar"),
    path('libro/libro_detail/<int:pk>/',
         LibroDetailView.as_view(), name="libro_ver_detalles"),
    path('libro/libros_filtrar', LibroViewFilter.as_view(), name="libros_filtrar"),

    path('autor/autores/', AutoresList.as_view(), name="autores"),
    path('autor/autor_agregar/',  AutorCreate.as_view(), name="autor_agregar"),
    path('autor/autor_confirm_delete/<int:pk>/',
         AutorDelete.as_view(), name="autor_eliminar"),
    path('autor/autor_actualizar/<int:pk>/',
         AutorUpdate.as_view(), name="autor_actualizar"),
    path('autor/autor_detail/<int:pk>/',
         AutorDetailView.as_view(), name="autor_ver_detalles"),
    path('autor/autores_filtrar',
         AutoresViewFilter.as_view(), name="autores_filtrar"),

    path('editorial/editoriales/', EditorialesList.as_view(), name="editoriales"),
    path('editorial/editorial_agregar/',
         EditorialCreate.as_view(), name="editorial_agregar"),
    path('editorial/editorial_confirm_delete/<int:pk>/',
         EditorialDelete.as_view(), name="editorial_eliminar"),
    path('editorial/editorial_actualizar/<int:pk>/',
         EditorialUpdate.as_view(), name="editorial_actualizar"),
    path('editorial/editorial_detail/<int:pk>/',
         EditorialDetailView.as_view(), name="editorial_ver_detalles"),
    path('editorial/editoriales_filtrar',
         EditorialViewFilter.as_view(), name="editoriales_filtrar"),

    path('genero/generos/', GenerosList.as_view(), name="generos"),
    path('genero/genero_agregar/',   GeneroCreate.as_view(), name="genero_agregar"),
    path('genero/genero_confirm_delete/<int:pk>/',
         GeneroDelete.as_view(), name="genero_eliminar"),
    path('genero/genero_actualizar/<int:pk>/',
         GeneroUpdate.as_view(), name="genero_actualizar"),
    path('genero/genero_detail/<int:pk>/',
         GeneroDetailView.as_view(), name="genero_ver_detalles"),
    path('genero/generos_filtrar',
         GenerosViewFilter.as_view(), name="generos_filtrar"),


    path('acerca_de_mi', AcercaDeMi.as_view(), name="acerca_de_mi"),

]

proyecto_libreria/proyecto_libreria/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto_libreria import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('libros_app.urls', 'libros_app'), namespace='libros_app')),
    path('', include(('usuarios_app.urls', 'usuarios_app'), namespace='usuarios_app')),
    ]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

proyecto_libreria/libros_app/models.py
from django.db import models
from django.contrib import admin
from django.utils.html import format_html
from django.utils import timezone

# Create your models here.

# Editorial del libro.


class Editorial(models.Model):
    nombre = models.CharField(verbose_name="Editorial", max_length=50)
    foto = models.ImageField(upload_to="editoriales",
                             null=True, blank=True, verbose_name="Editorial")
    ano = models.SmallIntegerField(
        verbose_name="Año de fundacion", blank=True, default=0)
    historia = models.TextField(verbose_name="Historia")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Editorial"
        verbose_name_plural = "Editoriales"

    def __str__(self):
        return self.nombre

    @admin.display(ordering="Historia")
    def Historia(self):
        return format_html(self.historia[:150]+"...")

# Autor del libro.


class Autor(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=50)
    Apellido = models.CharField(verbose_name="Apellido", max_length=50)
    foto = models.ImageField(
        upload_to="autores", null=True, blank=True, verbose_name="Autor")
    fecha_nacimiento = models.DateField(default=timezone.now)
    biografia = models.TextField(verbose_name="Biografía")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

    def __str__(self):
        return self.nombre + " " + self.Apellido

    @admin.display(ordering="biografia")
    def sinopsis(self):
        return format_html(self.description[:150]+"...")

# Género de los libros.


class Genero(models.Model):
    nombre = models.CharField(verbose_name="Género", max_length=50)
    historia = models.TextField(verbose_name="Historia", default="")
    foto = models.ImageField(
        upload_to="generos", null=True, blank=True, verbose_name="Género")

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Género"
        verbose_name_plural = "Géneros"

    def __str__(self):
        return self.nombre

# Libro.


class Libro(models.Model):
    nombre = models.CharField(verbose_name="Libro", max_length=100)
    autor = models.ManyToManyField(Autor, verbose_name="Autores")
    sinopsis = models.TextField(verbose_name="sinopsis", blank=True)

    RATING = [
        (1, "Malo"),
        (2, "Mediocre"),
        (3, "Bueno"),
        (4, "Muy Bueno"),
        (5, "Excelente"),
    ]

    rating = models.PositiveSmallIntegerField(choices=RATING)
    generos = models.ManyToManyField(Genero, verbose_name="Géneros")
    editorial = models.ForeignKey(
        Editorial, verbose_name="Editorial", on_delete=models.CASCADE)
    portada = models.ImageField(
        upload_to="libros", null=True, blank=True, verbose_name="Portada")
    ano_publicacion = models.SmallIntegerField(
        verbose_name="Año de publicacion", blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Libro"
        verbose_name_plural = "Libros"

    def __str__(self):
        return self.nombre

    @admin.display(ordering="rating")
    def estrellas(self):
        stars = "*" * self.rating
        return format_html(f"<span style='color:green;'>{stars}</span>")

    @admin.display(ordering="sinopsis")
    def descripcion(self):
        return format_html(self.description[:150]+"...")

    def get_generos(self):
        return ",".join([str(p) for p in self.generos.all()])

    def get_autores(self):
        return ",".join([str(p) for p in self.autor.all()])

proyecto_libreria/libros_app/forms.py
from django import forms
from .models import Editorial, Autor, Genero, Libro


class LibroForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LibroForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Libro

        fields = ['nombre', 'autor', 'sinopsis', 'rating',
                  'generos', 'editorial', 'portada', 'ano_publicacion']
        RATING = [
            (1, "Mala"),
            (2, "Mediocre"),
            (3, "Buena"),
            (4, "Muy Buena"),
            (5, "Excelente")
        ]
        widgets = {
            'Nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Libro'}),
            'Autores': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Géneros'}),
            'sinopsis': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Libro'}),
            'rating': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Rating'}),
            'generos': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Géneros'}),
            'editorial': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Editorial'}),
            'ano_publicacion': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Año de publicacion'}),
        }

        labels = {
            'name': "",
            'description': ""
        }


class AutorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AutorForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Autor

        fields = ['nombre', 'Apellido', 'foto',
                  'fecha_nacimiento', 'biografia']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'Apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'fecha_nacimiento': forms.DateInput(format='%d/%m/%Y'),
            'biografia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Biografía'}),

        }

        labels = {
            'name': "",
            'description': ""
        }


class EditorialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditorialForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Editorial

        fields = ['nombre', 'ano', 'historia', 'foto']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'ano': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Año de fundación'}),
            'historia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Historia'}),
        }

        labels = {
            'name': "",
            'description': ""
        }


class GeneroForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GeneroForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Genero

        fields = ['nombre', 'historia', 'foto']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'historia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Historia'}),
        }

        labels = {
            'name': "",
            'description': ""
        }

proyecto_libreria/libros_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages


import django_filters

# Create your views here.

# Importaciones de Modelos

from .models import Editorial, Autor, Genero, Libro


from .forms import LibroForm, AutorForm, EditorialForm, GeneroForm

from .filters import LibroFilter, AutorFilter, EditorialFilter, GeneroFilter


# Importaciones de CBV

from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import DetailView


from django_filters.views import FilterView


# CLASS BASED VIEWS

class HomeView(TemplateView):
    template_name = "libros_app/inicio.html"


class LibrosList(ListView):
    model = Libro
    template_name = "libros_app/libro/libro_list.html"


class LibroDetailView(DetailView):
    model = Libro
    template_name = "libros_app/libro/libro_detail.html"


class LibroCreate(CreateView):
    model = Libro
    form_class = LibroForm
    success_url = reverse_lazy('libros_app:libros')
    template_name = "libros_app/libro/libro_form.html"


class LibroDelete(DeleteView):
    model = Libro
    success_url = reverse_lazy('libros_app:libros')
    template_name = "libros_app/libro/libro_confirm_delete.html"


class LibroUpdate(UpdateView):
    model = Libro
    form_class = LibroForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/libro/libro_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:libro_actualizar', args=[self.object.id])+"?ok"


class LibroViewFilter(FilterView):
    model = Libro
    template_name = 'libros_app/libro/libros_filtrar.html'
    paginate_by = 10
    filterset_class = LibroFilter


class AutoresList(ListView):
    model = Autor
    template_name = "libros_app/autor/autor_list.html"


class AutorDetailView(DetailView):
    model = Autor
    template_name = "libros_app/autor/autor_detail.html"


class AutorCreate(CreateView):
    model = Autor
    form_class = AutorForm
    success_url = reverse_lazy('libros_app:autores')
    template_name = "libros_app/autor/autor_form.html"


class AutorDelete(DeleteView):
    model = Autor
    success_url = reverse_lazy('libros_app:autores')
    template_name = "libros_app/autor/autor_confirm_delete.html"


class AutorUpdate(UpdateView):
    model = Autor
    form_class = AutorForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/autor/autor_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:autor_actualizar', args=[self.object.id])+"?ok"


class AutoresViewFilter(FilterView):
    model = Autor
    template_name = 'libros_app/autor/autores_filtrar.html'
    paginate_by = 10
    filterset_class = AutorFilter


class EditorialesList(ListView):
    model = Editorial
    template_name = "libros_app/editorial/editorial_list.html"


class EditorialDetailView(DetailView):
    model = Editorial
    template_name = "libros_app/editorial/editorial_detail.html"


class EditorialCreate(CreateView):
    model = Editorial
    form_class = EditorialForm
    success_url = reverse_lazy('libros_app:editoriales')
    template_name = "libros_app/editorial/editorial_form.html"


class EditorialDelete(DeleteView):
    model = Editorial
    success_url = reverse_lazy('libros_app:editoriales')
    template_name = "libros_app/editorial/editorial_confirm_delete.html"


class EditorialUpdate(UpdateView):
    model = Editorial
    form_class = EditorialForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/editorial/editorial_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:editorial_actualizar', args=[self.object.id])+"?ok"


class EditorialViewFilter(FilterView):
    model = Editorial
    template_name = 'libros_app/editorial/editoriales_filtrar.html'
    paginate_by = 10
    filterset_class = EditorialFilter


class GenerosList(ListView):
    model = Genero
    template_name = "libros_app/genero/genero_list.html"


class GeneroDetailView(DetailView):
    model = Genero
    template_name = "libros_app/genero/genero_detail.html"


class GeneroCreate(CreateView):
    model = Genero
    form_class = GeneroForm
    success_url = reverse_lazy('libros_app:generos')
    template_name = "libros_app/genero/genero_form.html"


class GeneroDelete(DeleteView):
    model = Genero
    success_url = reverse_lazy('libros_app:generos')
    template_name = "libros_app/genero/genero_confirm_delete.html"


class GeneroUpdate(UpdateView):
    model = Genero
    form_class = GeneroForm
    template_name_suffix = "_update_form"
    template_name = "libros_app/genero/genero_update_form.html"

    def get_success_url(self):
        return reverse_lazy('libros_app:genero_actualizar', args=[self.object.id])+"?ok"


class GenerosViewFilter(FilterView):
    model = Genero
    template_name = 'libros_app/genero/generos_filtrar.html'
    paginate_by = 10
    filterset_class = GeneroFilter


class AcercaDeMi(TemplateView):
    template_name = "libros_app/acerca_de_mi.html"

proyecto_libreria/libros_app/templates/libros_app/autor/autor_confirm_delete.html
{% extends 'libros_app/base.html' %}
{% load static %}

{% block title %}
  Eliminar Autor
{% endblock %}

{% block content %}
  {% include 'libros_app/autor/includes/admin_menu_autores.html' %}
  <div class="container-xxl py-3">
    <div class="container">
      <h1>Eliminar autores</h1>
      <form method="post">
        {% csrf_token %}
        <p>¿Esta seguro que quiere eliminar al autor "{{ object }}"?</p>
        {% comment %} {{ form }} {% endcomment %}
        <input type="submit" value="Confirmar" />
      </form>
    </div>
  </div>
{% endblock %}

proyecto_libreria/libros_app/templates/libros_app/autor/autor_detail.html
{% extends 'libros_app/base.html' %}

{% load static %}

{% block title %}
  Autor.nombre
{% endblock %}

{% block content %}
  {% include 'libros_app/autor/includes/admin_menu_autores.html' %}

  <div class="container-xxl py-5">
    <div class="container">
      <div class="row g-5 align-items-start">
        <div class="col-lg-6 animated fadeIn" data-wow-delay="0.1s">
          <div class="property-item rounded about-img position-relative overflow-hidden p-5 pe-0">
            {% if autor.foto %}
              <img class="img-fluid imagen-detalle" src="{{ autor.foto.url }}" />
            {% else %}
              <img class="img-fluid imagen-detalle" src="{% static 'libros_app/images/usuarionodisponible.png' %}" alt="" />
            {% endif %}
          </div>
        </div>
        <div class="col-lg-6 animated fadeIn" data-wow-delay="0.5s">
          <h1 class="mb-4">{{ autor.nombre }} {{ autor.Apellido }}</h1>
          <p class="mb-4">
            <b>Biografia:</b> {{ autor.biografia }}
          </p>
          <p class="mb-4">
            <b>Fecha de nacimiento:</b> {{ autor.fecha_nacimiento }}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

proyecto_libreria/libros_app/templates/libros_app/autor/autor_form.html
{% extends 'libros_app/base.html' %}

{% load static %}

{% block title %}
  Agregar autores
{% endblock %}

{% block subMenu %}
  <div class="row g-0 gx-5 align-items-end">
    <div class="col text-start text-lg-end animated slideInRight" data-wow-delay="0.1s">
      <ul class="nav nav-pills d-inline-flex justify-content-end mb-5">
        {% if request.user.is_staff %}
          <li class="nav-item me-2">
            <a class="btn btn-outline-primary" href="{% url 'libros_app:autores' %}">Listar</a>
          </li>
          <li class="nav-item me-2">
            <a class="btn btn-outline-primary active" href="{% url 'libros_app:autor_agregar' %}">Agregar</a>
          </li>
        {% endif %}
        <li class="nav-item me-0">
          <a class="btn btn-outline-primary" href="{% url 'libros_app:autores_filtrar' %}">Filtrar</a>
        </li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container-xxl py-3">
    <div class="container">
      <h1>Agregar autor</h1>

      <form action="" method="post" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" class="btn btn-primary py-2 px-5 me-3" style="width: 100%; margin-top:10px;" value="Agregar autor" />
      </form>
    </div>
  </div>
{% endblock %}

proyecto_libreria/libros_app/templates/libros_app/autor/autor_list.html
{% extends 'libros_app/base.html' %}

{% load static %}

{% block title %}
  Autores
{% endblock %}

{% block subMenu %}
  <div class="row g-0 gx-5 align-items-end">
    <div class="col text-start text-lg-end animated slideInRight" data-wow-delay="0.1s">
      <ul class="nav nav-pills d-inline-flex justify-content-end mb-5">
        {% if request.user.is_staff %}
          <li class="nav-item me-2">
            <a class="btn btn-outline-primary active" href="{% url 'libros_app:autores' %}">Listar</a>
          </li>
          <li class="nav-item me-2">
            <a class="btn btn-outline-primary" href="{% url 'libros_app:autor_agregar' %}">Agregar</a>
          </li>
        {% endif %}
        <li class="nav-item me-0">
          <a class="btn btn-outline-primary" href="{% url 'libros_app:autores_filtrar' %}">Filtrar</a>
        </li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container-xxl py-3">
    <div class="container">
      <div class="row g-0 gx-5 align-items-end">
        <h1>Autores</h1>
        {% if autor_list %}
          <div class="row">
            {% for autor in autor_list %}
              <div class="col-lg-4 col-md-6 animated fadeInUp" data-wow-delay="0.1s">
                <div class="property-item rounded overflow-hidden">
                  <div class="position-relative overflow-hidden centrar-items">
                    {% if autor.foto %}
                      <a href="{% url 'libros_app:autor_ver_detalles' autor.id %}"><img class="img-fluid imagen" src="{{ autor.foto.url }}" alt="{{ autor.foto.url }}" alt="" /></a>
                    {% else %}
                      <a href="{% url 'libros_app:autor_ver_detalles' autor.id %}"><img class="img-fluid imagen" src="{% static 'libros_app/images/usuarionodisponible.png' %}" alt="" /></a>
                    {% endif %}
                  </div>
                  <div class="p-5 pb-5">
                    {% if request.user.is_staff %}
                      <div class="" style="float :right ; ">
                        <a class="btn btn-outline-primary" href="{% url 'libros_app:autor_actualizar' autor.id %}">Editar</a>
                        <a class="btn btn-outline-primary" href="{% url 'libros_app:autor_eliminar' autor.id %}">Eliminar</a>
                      </div>
                    {% endif %}
                    <a class="d-block h5 mb-2" href="">{{ autor.nombre }} {{ autor.Apellido }}</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        {% else %}
          <p class="card-text">No hay ningun autor por el momento, vuelva pronto, lo estamos esperando!</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

proyecto_libreria/libros_app/templates/libros_app/autor/autor_update_form.html
{% extends 'libros_app/base.html' %}

{% load static %}

{% block title %}
  Modificar autor
{% endblock %}

{% block content %}
  {% include 'libros_app/autor/includes/admin_menu_autores.html' %}
  <div class="container-xxl py-3">
    <div class="container">
      <h1>Editar autores</h1>

      {% if 'ok' in request.GET %}
        <p class="alert alert-info">Autor modificado correctamente</p>
      {% endif %}

      <form action="" method="post" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        {% if autor.foto %}
          <img class="img-fluid imagen" src="{{ autor.foto.url }}" />
        {% else %}
          <img class="img-fluid imagen" src="{% static 'libros_app/images/usuarionodisponible.png' %}" alt="" />
        {% endif %}

        <input type="submit" class="btn btn-primary py-2 px-5 me-3" style="width: 100%; margin-top:10px;" value="Modificar autor" />
      </form>
    </div>
  </div>
{% endblock %}

proyecto_libreria/libros_app/templates/libros_app/autor/autores_filtrar.html
{% extends 'libros_app/base.html' %}

{% block title %}
  Filtrar Autor
{% endblock %}

{% block subMenu %}
  <div class="row g-0 gx-5 align-items-end">
    <div class="col text-start text-lg-end animated slideInRight" data-wow-delay="0.1s">
      <ul class="nav nav-pills d-inline-flex justify-content-end mb-5">
        {% if request.user.is_staff %}
          <li class="nav-item me-2">
            <a class="btn btn-outline-primary" href="{% url 'libros_app:autores' %}">Listar</a>
          </li>
          <li class="nav-item me-2">
            <a class="btn btn-outline-primary" href="{% url 'libros_app:autor_agregar' %}">Agregar</a>
          </li>
        {% endif %}
        <li class="nav-item me-0">
          <a class="btn btn-outline-primary active" href="{% url 'libros_app:autores_filtrar' %}">Filtrar</a>
        </li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <title>Filtrar autores</title>
  <div class="container-xxl py-3">
    <div class="container">
      <h1>Filtrar autores</h1>
      <form method="get">
        {% csrf_token %}
        {% for field in filter.form %}
          {{ field.label_tag }}
          {{ field }}
        {% endfor %}
        <button type="submit" class="btn btn-primary py-2 px-5 me-3" style="width: 100%; margin-top:10px;" style="margin-top: 10px;">Filter</button>
      </form>
    </div>
  </div>

  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">nombre</th>
          <th scope="col">apellido</th>
          <th scope="col">biografia</th>
          <th scope="col">fecha de nacimiento</th>
        </tr>
      </thead>
      <tbody>
        {% for autor in filter.qs %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ autor.nombre }}</td>
            <td>{{ autor.Apellido }}</td>
            <td>{{ autor.biografia }}</td>
            <td>{{ autor.fecha_nacimiento }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}